[package]
name = "rustcrypt"
version = "0.1.0-beta.1"
edition = "2021"
authors = ["Arthur Bernard"]
description = "runtime-safe AES-GCM for sensitive data"
license = "Unlicense"
readme = "README.md"
documentation = "https://docs.rs/rustcrypt"
keywords = [
    "crypto",
    "cryptography",
    "encryption",
    "decryption",
    "aes",
    "aes-gcm",
    "argon2",
    "kdf",
    "key-derivation",
    "authenticated-encryption",
    "layered-encryption",
    "password-based-encryption",
    "runtime-decryption",
    "obfuscator",
    "security",
    "secure-storage",
    "cipher",
    "ciphersuite",
    "secret-management",
    "data-protection",
    "confidentiality",
    "integrity",
    "privacy",
    "secure-communication",
    "rustcrypt"
]
categories = ["cryptography"]

[dependencies]
aes-gcm = { version = "0.10", features = ["aes"] }
chacha20poly1305 = { version = "0.10", features = ["alloc"] }
rand = "0.8"
rand_core = "0.6"
getrandom = "0.2"
zeroize = { version = "1.7", features = ["zeroize_derive"] }
hkdf = "0.12"
sha2 = "0.10"
base64 = "0.22"
secrecy = "0.8"


[lib]
name = "rustcrypt"
path = "src/lib.rs"

[features]
default = []
ephemeral-sessions = []

